services:
  db:
    image: postgis/postgis:15-3.3
    container_name: carkie_postgis
    environment:
      POSTGRES_USER: carkie_user
      POSTGRES_PASSWORD: carkie_secure_pass
      POSTGRES_DB: carkie_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carkie_user -d carkie_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: